# Mainnet Configuration for Service Quality Oracle
# BigQuery Configuration
BIGQUERY_LOCATION_ID: "US"
BIGQUERY_PROJECT_ID: "graph-mainnet"
BIGQUERY_DATASET_ID: "internal_metrics"
BIGQUERY_TABLE_ID: "metrics_indexer_attempts"
BIGQUERY_CURATION_TABLE_ID: "metrics_curator_signals"
BIGQUERY_CURATOR_MAINNET_TABLE_ID: "curator_name_signal_dimensions_daily"
BIGQUERY_CURATOR_ARBITRUM_TABLE_ID: "curator_name_signal_dimensions_arbitrum_daily"
BIGQUERY_SUBGRAPH_LOOKUP_TABLE_ID: "subgraph_version_id_lookup"
BIGQUERY_ANALYSIS_PERIOD_DAYS: "28"

# Blockchain Configuration (Arbitrum One - Mainnet)
BLOCKCHAIN_CONTRACT_ADDRESS: "0x0000000000000000000000000000000000000000"  # TODO: Replace with mainnet contract
BLOCKCHAIN_FUNCTION_NAME: "allowIndexers"
BLOCKCHAIN_CHAIN_ID: "42161"
BLOCK_EXPLORER_URL: "https://arbiscan.io"
TX_TIMEOUT_SECONDS: "30"

# RPC Provider URLs (Arbitrum One - Mainnet)
BLOCKCHAIN_RPC_URL_1: "https://arbitrum.drpc.org"
BLOCKCHAIN_RPC_URL_2: "https://arb1.arbitrum.io/rpc"  
BLOCKCHAIN_RPC_URL_3: "https://api.zan.top/node/v1/arb/one"
BLOCKCHAIN_RPC_URL_4: "https://arbitrum-one.gateway.tenderly.co"

# Scheduling Configuration
SCHEDULED_RUN_TIME: "10:00"

# Subgraph URLs
SUBGRAPH_URL_PRE_PRODUCTION: "https://api.studio.thegraph.com/query/110664/issuance-eligibility-oracle/v0.1.4"
SUBGRAPH_URL_PRODUCTION: "https://gateway.thegraph.com/api/subgraphs/id/"

# Processing Configuration
BATCH_SIZE: "125"
MAX_AGE_BEFORE_DELETION: "120"

# Caching Configuration
CACHE_MAX_AGE_MINUTES: "30"
FORCE_BIGQUERY_REFRESH: "false"

# Eligibility Criteria
MIN_ONLINE_DAYS: "5"
MIN_SUBGRAPHS: "10"
MAX_LATENCY_MS: "5000"
MAX_BLOCKS_BEHIND: "50000"
MIN_CURATION_SIGNAL: "500"

# Runtime Configuration
RUN_ON_STARTUP: "true"
