apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-quality-oracle
  labels:
    app: service-quality-oracle
  annotations:
    iam.gke.io/gcp-service-account: service-quality-oracle@graph-mainnet.iam.gserviceaccount.com
automountServiceAccountToken: false
